import { NewsData } from "@/shared/models/newsData";
import { Metadata } from "next";
import { SearchLayout } from "@/shared/components/pages/searchLayout";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Search({
}) {
  return <Suspense><SearchLayout data={NewsData[0]}/></Suspense>;
}
