import { Metadata } from "next";
import { DocsLayout } from "@/shared/components/pages/docsLayout";
import { Privacy } from "@/shared/models/documents";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Agreement() {
  return (
    <DocsLayout data={Privacy} title="Пользовательское соглашение" />
  );
}