import { Metadata } from "next";
import { Head } from "@/shared/components/shared/head";
import { DocsLayout } from "@/shared/components/shared/docsLayout";
import { Privacy } from "@/shared/models/documents";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Agreement() {
  return (
    <main>
    <Head breadcrumbs title="Пользовательское соглашение" />
    <DocsLayout data={Privacy}/>
    </main>
  );
}