import { NewsData } from "@/shared/models/newsData";
import { Metadata } from "next";
import { AboutData } from "@/shared/models/about";
import { AboutLayout } from "@/shared/components/pages/aboutLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <AboutLayout newsData={NewsData} aboutData={AboutData} />
  );
}
