import { Cards } from "@cmp/shared/cards/cards";
import { NewsData } from "@/shared/models/newsData";
import { PromoCards } from "@cmp/shared/promo/cards";
import { Metadata } from "next";
import { Head } from "@/shared/components/shared/head";
import { Line } from "@/shared/components/shared/line";
import React from "react";
import { HeadWSort } from "@/shared/components/shared/cards/head-w-sort";
import Form from "@/shared/components/shared/about/form";
import { Contact } from "@/shared/components/shared/contact";
import { AboutUs } from "@/shared/components/shared/about/about";
import { ContactInfo } from "@/shared/components/shared/about/contact-info";
import { AboutData } from "@/shared/models/about";
import { DataCardAbout, IContact, IContactInfo, SocialItem } from "@/shared/interface/IAbout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <Head breadcrumbs title="О нас" />
     <AboutUs data={AboutData.find((item) => item.slug === "О нас") as DataCardAbout} />
      <div className="about__row">
        {(() => {
          const info = AboutData.find(
            (item) => item.slug === "Контактная информация"
          )?.data as IContactInfo;

          const soc = AboutData.find(
            (item) => item.slug === "Социальные сети"
          )?.data as SocialItem[];

          return info && <ContactInfo soc={soc} {...info} />;
        })()}
        <Form />
      </div>
      <Line />
      <div className="about__contacts">
        {(
          (AboutData.find((item) => item.slug === "Контакты")?.data ||
            []) as IContact[]
        ).map((contact) => (
          <Contact
            key={contact.title}
            title={contact.title}
            contact={contact.contact}
            mail={contact.mail}
            className="about__contacts-item"
          />
        ))}
      </div>
      <Line />
      <div className="page__column">
        <HeadWSort title="Все новости" />
        {NewsData.map((cards, index) => {
          const isLast = index === NewsData.length - 1;
          return (
            <React.Fragment key={cards.title}>
              <Cards data={cards} />
              {!isLast && <Line />}
              {index === 0 && (
                <React.Fragment>
                  <PromoCards />
                  <Line />
                </React.Fragment>
              )}
            </React.Fragment>
          );
        })}
      </div>
    </main>
  );
}
