import { NewsItemData } from "@/shared/models/newsItemData";
import { Metadata } from "next";
import { NewsPageLayout } from "@/shared/components/pages/newsPageLayout";
import { NewsData } from "@/shared/models/newsData";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <NewsPageLayout data={NewsItemData} newsData={NewsData} />
  );
}