import { NewsItemData } from "@/shared/models/newsItemData";
import { Metadata } from "next";
import { NewsPage } from "@/shared/components/shared/news/news";
import { NewsData } from "@/shared/models/newsData";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageNews() {
  return (
    <NewsPage data={NewsItemData} newsData={NewsData} />
  );
}