import type { Metadata } from "next";
import '../shared/styles/app.scss';
import { Header } from '@cmp/shared/header/header';
import { Footer } from "@cmp/shared/footer/footer";
import { Inter } from 'next/font/google';
import { NewsData } from "@/shared/models/newsData";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <meta name="format-detection" content="telephone=no" />
      </head>
      <body
        className={`${inter.className} antialiased`}
      >
        <Header data={NewsData}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
