import { NewsData } from "@/shared/models/newsData";
import { Metadata } from "next";
import React from "react";
import { MainLayout } from "@/shared/components/pages/mainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  // const region = searchParams.region ?? null;

  //  const data = await fetch(
  //   `${API}/home${region ? `?region=${region}` : ""}`
  // ).then(r => r.json());

  return <MainLayout data={NewsData} type="Новости"/>;
}
