import { NewsData } from "@/shared/models/newsData";
import { Metadata } from "next";
import React, { Suspense } from "react";
import { MainLayout } from "@/shared/components/pages/mainLayout";
import { NewsTopicLayout } from "@/shared/components/pages/newsTopicLayout";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function News({
  searchParams,
}: {
  searchParams: Promise<{ topic?: string }>;
}) {
  const resolvedSearchParams = await searchParams;

  if (resolvedSearchParams.topic) {
    const topicItem = NewsData.find(
      (item) => item.slug === resolvedSearchParams.topic,
    );
    if (!topicItem) notFound();
    return <Suspense><NewsTopicLayout type="Новости" data={topicItem} /></Suspense>;
  }

  return <MainLayout breadcrumbs data={NewsData} type="Новости" />;
}
