export const NewsData = [
  {
    title: "Власть",
    slug: "vlast",
    cardsData: [
      {
        id: "1",
        title: "Юрий Зайцев: «Для меня лично поддержка участников СВО была и остается одним из приоритетных направлений работы»",
        time: "15 минут",
        location: "Марий Эл",
        imageUrl: "/images/Guber.jpg",
      },
      {
        id: "1001",
        title: "Глава Марий Эл провел встречу с представителями малого бизнеса",
        time: "5 часов",
        location: "Марий Эл",
        imageUrl: "/images/Mariel.jpg",
      },
      {
        id: "46",
        title: "Минтимер Шаймиев принял участие в работе XX съезда Совета муниципальных образований РТ",
        time: "20 минут",
        location: "Татарстан",
        imageUrl: "/images/Tatarstan.jpg",
      },
      {
        id: "49",
        title: "Историческое наследие Казани: реставрация Казанского кремля продолжается",
        time: "3 часа",
        location: "Татарстан",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "2001",
        title: "Президент Татарстана встретился с главами муниципалитетов",
        time: "5 часов",
        location: "Татарстан",
        imageUrl: "/images/Mariel.jpg",
      },
      {
        id: "50",
        title: "Олег Николаев наградил представителей СМИ за вклад в развитие чувашской журналистики",
        time: "25 минут",
        location: "Чувашия",
        imageUrl: "/images/Chuvach.jpg",
      },
      {
        id: "53",
        title: "Транспортная система Чебоксар модернизируется: новые развязки сократят пробки",
        time: "4 часа",
        location: "Чувашия",
        imageUrl: "/images/Probka.jpg",
      },
      {
        id: "3001",
        title: "Глава Чувашии провел встречу с активистами",
        time: "6 часов",
        location: "Чувашия",
        imageUrl: "/images/Mariel.jpg",
      },
      {
        id: "54",
        title: "В Нижнем Новгороде возрождают уникальный Студёный квартал",
        time: "10 минут",
        location: "Нижний Новгород",
        imageUrl: "/images/Nizhegorod.webp",
      },
      {
        id: "57",
        title: "Архитектурный комплекс Нижегородского кремля отреставрируют к 800-летию города",
        time: "5 часов",
        location: "Нижний Новгород",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "4001",
        title: "Губернатор Нижегородской области встретился с бизнес-сообществом",
        time: "6 часов",
        location: "Нижний Новгород",
        imageUrl: "/images/Mariel.jpg",
      },
      {
        id: "401",
        title: "Губернатор Кировской области наградил лучших работников региона",
        time: "15 минут",
        location: "Киров",
        imageUrl: "/images/Kirov.jpg",
      },
      {
        id: "60",
        title: "Дорожная инфраструктура Кирова: ремонт ключевых магистралей завершен",
        time: "2 часа",
        location: "Киров",
        imageUrl: "/images/Probka.jpg",
      },
      {
        id: "5001",
        title: "Глава Кировской области провел прием граждан",
        time: "5 часов",
        location: "Киров",
        imageUrl: "/images/Mariel.jpg",
      },
    ],
  },
  {
    title: "Экономика",
    slug: "economics",
    cardsData: [
      {
        id: "10",
        title: "Строительство доступного жилья в Марий Эл увеличилось на 40% за год",
        time: "4 часа",
        location: "Марий Эл",
        imageUrl: "/images/Kvartir.jpg",
      },
      {
        id: "12",
        title: "В Марий Эл отремонтировали более 200 км региональных дорог",
        time: "5 часов",
        location: "Марий Эл",
        imageUrl: "/images/Probka.jpg",
      },
      {
        id: "1007",
        title: "Промышленное производство в Марий Эл выросло на 15%",
        time: "1 день",
        location: "Марий Эл",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "101",
        title: "Экономика Татарстана показывает рекордный рост",
        time: "1 час",
        location: "Татарстан",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "102",
        title: "Инвестиции в Татарстан выросли на 25%",
        time: "4 часа",
        location: "Татарстан",
        imageUrl: "/images/Probka.jpg",
      },
      {
        id: "2007",
        title: "Новый завод откроется в Набережных Челнах",
        time: "1 день",
        location: "Татарстан",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "51",
        title: "Завод «АвтоВАЗ» в Чувашии увеличил производство на 20%",
        time: "1 час",
        location: "Чувашия",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "203",
        title: "Малый бизнес Чувашии получил новые льготы",
        time: "5 часов",
        location: "Чувашия",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "3007",
        title: "Промышленное производство в Чувашии выросло на 18%",
        time: "1 день",
        location: "Чувашия",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "302",
        title: "Промышленность Нижегородской области показывает рост",
        time: "2 часа",
        location: "Нижний Новгород",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "303",
        title: "Инвестиции в регион достигли рекордных показателей",
        time: "вчера",
        location: "Нижний Новгород",
        imageUrl: "/images/Probka.jpg",
      },
      {
        id: "4007",
        title: "Автомобильный завод в Нижнем Новгороде увеличил выпуск",
        time: "1 день",
        location: "Нижний Новгород",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "58",
        title: "Кировская область получила федеральную поддержку на жилищное строительство",
        time: "15 минут",
        location: "Киров",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "404",
        title: "Экономика Кировской области демонстрирует стабильный рост",
        time: "вчера",
        location: "Киров",
        imageUrl: "/images/Lada.jpg",
      },
      {
        id: "5007",
        title: "Промышленное производство в области выросло на 10%",
        time: "1 день",
        location: "Киров",
        imageUrl: "/images/Lada.jpg",
      },
    ],
  },
  {
    title: "Общество",
    slug: "society",
    cardsData: [
      {
        id: "3",
        title: "Синоптики прогнозируют аномально теплую зиму в Марий Эл",
        time: "45 минут",
        location: "Марий Эл",
        imageUrl: "/images/Pogoda.jpg",
      },
      {
        id: "4",
        title: "Утренние пробки в Йошкар-Оле сократились после открытия новой развязки",
        time: "1 час",
        location: "Марий Эл",
        imageUrl: "/images/Probka.jpg",
      },
      {
        id: "1013",
        title: "Благотворительная акция в Марий Эл помогла 500 семьям",
        time: "1 день",
        location: "Марий Эл",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "105",
        title: "В Татарстане открылись новые социальные центры",
        time: "3 часа",
        location: "Татарстан",
        imageUrl: "/images/Pogoda.jpg",
      },
      {
        id: "106",
        title: "Культурные мероприятия в Казани собрали тысячи зрителей",
        time: "6 часов",
        location: "Татарстан",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "2013",
        title: "Благотворительный фонд Татарстана помог 1000 семей",
        time: "1 день",
        location: "Татарстан",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "52",
        title: "Температурный режим в Чувашии: синоптики прогнозируют холода до конца месяца",
        time: "2 часа",
        location: "Чувашия",
        imageUrl: "/images/Pogoda.jpg",
      },
      {
        id: "206",
        title: "Благотворительная акция в Чувашии помогла сотням семей",
        time: "вчера",
        location: "Чувашия",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "3013",
        title: "Культурный фестиваль в Чебоксарах стал событием года",
        time: "1 день",
        location: "Чувашия",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "305",
        title: "Социальные программы охватили тысячи жителей области",
        time: "3 часа",
        location: "Нижний Новгород",
        imageUrl: "/images/Pogoda.jpg",
      },
      {
        id: "306",
        title: "Фестиваль культуры в Нижнем Новгороде стал событием года",
        time: "вчера",
        location: "Нижний Новгород",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "4013",
        title: "Благотворительный фонд помог 800 семьям",
        time: "1 день",
        location: "Нижний Новгород",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "59",
        title: "В Кировской области ожидаются сильные снегопады на этой неделе",
        time: "1 час",
        location: "Киров",
        imageUrl: "/images/Pogoda.jpg",
      },
      {
        id: "406",
        title: "Благотворительные фонды Кирова помогли сотням семей",
        time: "вчера",
        location: "Киров",
        imageUrl: "/images/MarielGlava.jpg",
      },
      {
        id: "5013",
        title: "Культурный фестиваль в Кирове собрал полные залы",
        time: "1 день",
        location: "Киров",
        imageUrl: "/images/MarielGlava.jpg",
      },
    ],
  },
];
