import { Metadata } from "next";
import { AboutData } from "@/shared/models/about";
import { ContactsLayout } from "@/shared/components/pages/contactsLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Contacts() {
  return (
    <ContactsLayout aboutData={AboutData} />
  );
}